# Generated by Django 3.0.5 on 2020-12-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoAjax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_title',
            field=models.TextField(),
        ),
    ]
